version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build: .
    container_name: python_app
    restart: always
    environment:
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
